//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayClient.CVThanhService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChungLoaiOutput", Namespace="http://schemas.datacontract.org/2004/07/DienMayServices")]
    [System.SerializableAttribute()]
    public partial class ChungLoaiOutput : DienMayClient.CVThanhService.ChungLoaiInput {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TongSoLoaiField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TongSoLoai {
            get {
                return this.TongSoLoaiField;
            }
            set {
                if ((this.TongSoLoaiField.Equals(value) != true)) {
                    this.TongSoLoaiField = value;
                    this.RaisePropertyChanged("TongSoLoai");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChungLoaiInput", Namespace="http://schemas.datacontract.org/2004/07/DienMayServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DienMayClient.CVThanhService.ChungLoaiOutput))]
    public partial class ChungLoaiInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ten {
            get {
                return this.TenField;
            }
            set {
                if ((object.ReferenceEquals(this.TenField, value) != true)) {
                    this.TenField = value;
                    this.RaisePropertyChanged("Ten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CVThanhService.IChungLoaiService")]
    public interface IChungLoaiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/DocTatCa", ReplyAction="http://tempuri.org/IChungLoaiService/DocTatCaResponse")]
        System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput> DocTatCa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/DocTatCa", ReplyAction="http://tempuri.org/IChungLoaiService/DocTatCaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput>> DocTatCaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/DocTheoTen", ReplyAction="http://tempuri.org/IChungLoaiService/DocTheoTenResponse")]
        System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput> DocTheoTen(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/DocTheoTen", ReplyAction="http://tempuri.org/IChungLoaiService/DocTheoTenResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput>> DocTheoTenAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/DocTheoID", ReplyAction="http://tempuri.org/IChungLoaiService/DocTheoIDResponse")]
        DienMayClient.CVThanhService.ChungLoaiOutput DocTheoID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/DocTheoID", ReplyAction="http://tempuri.org/IChungLoaiService/DocTheoIDResponse")]
        System.Threading.Tasks.Task<DienMayClient.CVThanhService.ChungLoaiOutput> DocTheoIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/Them", ReplyAction="http://tempuri.org/IChungLoaiService/ThemResponse")]
        string Them(DienMayClient.CVThanhService.ChungLoaiInput entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/Them", ReplyAction="http://tempuri.org/IChungLoaiService/ThemResponse")]
        System.Threading.Tasks.Task<string> ThemAsync(DienMayClient.CVThanhService.ChungLoaiInput entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/Sua", ReplyAction="http://tempuri.org/IChungLoaiService/SuaResponse")]
        string Sua(DienMayClient.CVThanhService.ChungLoaiInput entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/Sua", ReplyAction="http://tempuri.org/IChungLoaiService/SuaResponse")]
        System.Threading.Tasks.Task<string> SuaAsync(DienMayClient.CVThanhService.ChungLoaiInput entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/Huy", ReplyAction="http://tempuri.org/IChungLoaiService/HuyResponse")]
        string Huy(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChungLoaiService/Huy", ReplyAction="http://tempuri.org/IChungLoaiService/HuyResponse")]
        System.Threading.Tasks.Task<string> HuyAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChungLoaiServiceChannel : DienMayClient.CVThanhService.IChungLoaiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChungLoaiServiceClient : System.ServiceModel.ClientBase<DienMayClient.CVThanhService.IChungLoaiService>, DienMayClient.CVThanhService.IChungLoaiService {
        
        public ChungLoaiServiceClient() {
        }
        
        public ChungLoaiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChungLoaiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChungLoaiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChungLoaiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput> DocTatCa() {
            return base.Channel.DocTatCa();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput>> DocTatCaAsync() {
            return base.Channel.DocTatCaAsync();
        }
        
        public System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput> DocTheoTen(string value) {
            return base.Channel.DocTheoTen(value);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DienMayClient.CVThanhService.ChungLoaiOutput>> DocTheoTenAsync(string value) {
            return base.Channel.DocTheoTenAsync(value);
        }
        
        public DienMayClient.CVThanhService.ChungLoaiOutput DocTheoID(int id) {
            return base.Channel.DocTheoID(id);
        }
        
        public System.Threading.Tasks.Task<DienMayClient.CVThanhService.ChungLoaiOutput> DocTheoIDAsync(int id) {
            return base.Channel.DocTheoIDAsync(id);
        }
        
        public string Them(DienMayClient.CVThanhService.ChungLoaiInput entity) {
            return base.Channel.Them(entity);
        }
        
        public System.Threading.Tasks.Task<string> ThemAsync(DienMayClient.CVThanhService.ChungLoaiInput entity) {
            return base.Channel.ThemAsync(entity);
        }
        
        public string Sua(DienMayClient.CVThanhService.ChungLoaiInput entity) {
            return base.Channel.Sua(entity);
        }
        
        public System.Threading.Tasks.Task<string> SuaAsync(DienMayClient.CVThanhService.ChungLoaiInput entity) {
            return base.Channel.SuaAsync(entity);
        }
        
        public string Huy(int id) {
            return base.Channel.Huy(id);
        }
        
        public System.Threading.Tasks.Task<string> HuyAsync(int id) {
            return base.Channel.HuyAsync(id);
        }
    }
}
