//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DienMayServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChungLoai
    {
        public ChungLoai()
        {
            this.Loais = new HashSet<Loai>();
        }
    
        public int ChungLoaiID { get; set; }
        public string Ten { get; set; }
        public string BiDanh { get; set; }
    
        public virtual ICollection<Loai> Loais { get; set; }
    }
}
